version: '2'
services:
  zookeeper:
    image: linkerrepository/zookeeper:1.0.1
    network_mode: host
    command: /init.sh
    env_file: .env
    privileged: true
    restart: always
    environment:
     - "constraint:master==true"
     - "affinity:container!=*zookeeper*"

  mesosmaster:
    image: linkerrepository/mesos-master:0.28.1
    network_mode: host
    command: /entrypoint.sh
    env_file: .env
    volumes:
     - /var/lib/mesos/:/var/lib/mesos
    depends_on:
     - zookeeper
    privileged: true
    restart: always
    environment:
     - MESOS_LOG_DIR=/var/log/mesos
     #- MESOS_REGISTRY=in_memory
     - MESOS_WORK_DIR=/var/lib/mesos/master
     - "constraint:master==true"
     - "affinity:container!=*mesosmaster*"

  marathon:
    image: linkerrepository/marathon:1.1.1
    network_mode: host
    command: /entrypoint.sh
    env_file: .env
    depends_on:
     - zookeeper
    privileged: true
    restart: always
    environment:
     - MARATHON_TASK_LAUNCH_TIMEOUT=900000
     - "constraint:master==true"
     - "affinity:container!=*marathon*"


  mesosslave:
    image: linkerrepository/mesos-slave:0.28.1
    volumes:
     - /sys/fs/cgroup:/sys/fs/cgroup
     - /var/run/docker.sock:/var/run/docker.sock
     - /usr/local/bin:/usr/local/bin
     - /var/lib/mesos:/var/lib/mesos
     - /tmp:/tmp
     - /opt/mesosphere:/opt/mesosphere
    network_mode: host
    command: /entrypoint.sh
    env_file: .env
    depends_on:
     - zookeeper
    privileged: true
    restart: always
    environment:
     - MESOS_CONTAINERIZERS=docker,mesos
     - MESOS_LOG_DIR=/var/log/mesos
     - MESOS_WORK_DIR=/var/lib/mesos/slave
     - MESOS_LOGGING_LEVEL=INFO
     - MESOS_EXECUTOR_REGISTRATION_TIMEOUT=15mins
     - "constraint:slave==true"
     - "affinity:container!=*mesosslave*"

  dnsserver:
    image: linkerrepository/linker_mesos_dns:1.0.0
    volumes:
    - /linker/config:/linker/config
    network_mode: host
    env_file: .env
    depends_on:
     - zookeeper
    privileged: true
    restart: always
    environment:
     - "constraint:master==true"
     - "affinity:container!=*dnsserver*"

  adminrouter:
    image: linkerrepository/linker_router:1.0.0
    network_mode: host
    depends_on:
     - genresolvconf
    restart: always
    environment:
     - "constraint:master==true"
     - "constraint:adminrouter==true"
     - "affinity:container!=*adminrouter*"

  genresolvconf:
    image: linkerrepository/linker_resolver:1.0.0
    volumes:
    - /etc/resolv.conf:/etc/resolv.conf
    network_mode: host
    env_file: .env
    depends_on:
     - dnsserver
    restart: always
    environment:
     - RESOLVERS=8.8.8.8
     - "affinity:container!=*genresolvconf*"
